### ISSUE TITLE
Q1) Inflation 의 정확히 어떤 걸 뜻할까요?

### ISSUE THREAD

**Issue by ows3090** [KamaTAEWOO/FastCampusStudy-1#1]

**Comment by KamaTAEWOO** [comment]
1. XML 레이아웃 파일을 메모리에 객체화하는 과정을 의미
2. 뷰를 생성하는 가장 일반적인 방법
3. 인플레이션을 통해 생성된 뷰 객체를 이용하여 UI를 구성하고, 뷰에 이벤트 리스너를 등록하거나 애니메이션을 적용할 수 있음.

**Comment by ows3090** [comment]
@KamaTAEWOO 태우님
그럼 인플레이션을 하는 대표적인 메소드가 뭐가 있나요?

**Comment by KamaTAEWOO** [comment]
@ows3090 setContentView()입니다! 여기에 R.layout.(XmlFileName)을 사용하면 View와 연결 가능합니다.

**Comment by ows3090** [comment]
@KamaTAEWOO 맞습니다 태우님
https://velog.io/@ows3090/Android-findViewById-%EC%9B%90%EB%A6%AC
추가로 findViewById에 대한 글을 예전에 작성했는데 한번 읽어보셔도 좋을 것 같습니다!

**Comment by KamaTAEWOO** [comment]
넵넵! 자료 너무 감사합니다 ㅎㅎ
