### ISSUE TITLE
Q2) onSavedInstanceState는 왜 사용하는걸까요?

### ISSUE THREAD

**Issue by ows3090** [KamaTAEWOO/FastCampusStudy-1#2]

**Comment by KamaTAEWOO** [comment]
1. 사용자가 액티비티를 일시 중지하고 다른 액티비티로 전환할 때
2. 액티비티가 시스템에 의해 종료될 때
3. 사용자가 디바이스를 회전할 때(회전을 하면 데이터가 날라가는데 이것을 대처할 수 있음)
4. 사용자가 다국어 설정을 변경할 때
5. 상태를 저장하는 역할
6. 액티비티의 데이터를 보존할 수 있음(key - value 형태)

**Comment by ows3090** [comment]
@KamaTAEWOO 태우님
위의 예시일 경우에 onSaveldInstanceState가 필요하다는거죠?
그럼 사용했을 때 어떤 장점이 있는건가요?

**Comment by KamaTAEWOO** [comment]
@ows3090 강의에서는 디바이스 회전 시 값이 초기화 되지만, onSavedInstanceState()를 사용 시 필요한 값을 저장하여  다시 불러올 수 있는 함수입니다! 좀 더 공부해서 이 부분도 다시 쓰겠습니다.

**Comment by ows3090** [comment]
@KamaTAEWOO 태우님
말씀하신게 맞아요. 디바이스 회전 뿐만 아니라 해상도를 변경한다거나 하면 Configuration Change(구성변경)이 발생하여
Activity가 onDestory까지 진입 후 다시 onCreate 가 됩니다.
하지만 사용자에게는 구성변경이 일어나더라도 기존에 보여줬던 화면이 유지되어야 하기에 onSavedInstanceState나 ViewModel을 사용하여 유지하는 것입니다.
