### ISSUE TITLE
Q3) lateinit 은 언제 사용하나요? 예시와 함께 보여주세요

### ISSUE THREAD

**Issue by ows3090** [KamaTAEWOO/FastCampusStudy-1#3]

**Comment by KamaTAEWOO** [comment]
늦은 초기화, 나중에 초기화 가능

class Person {
   lateinit var name: String

   fun init() {
         name = "John"
   }

   fun printName() {
         if(name.isInitalized) {
              print(name)
         } else {
              print("name is not initalized yet.")
        }
    }
    
   fun main() {
       val person = Person()
       person.printName()
       preson.init()
       person.printName()
   }

**Comment by KamaTAEWOO** [comment]
1. 의존성 주입을 위한 프로퍼티 의존성 주입에서는 객체가 생성되는 시점에 모든 의존성이 초기화되지 않을 수 있음
2. 라이프사이클에 따라 초기화의 시점을 변경해야할 수도 있음
3. View를 늦게 초기화 할 수 있음. 매번 호출하면 메모리 낭비
4. 초기화에 필요한 데이터를 불러올 때까지 프로퍼티를 초기화할 수 있음.

**Comment by ows3090** [comment]
@KamaTAEWOO 태우님
스스로 이해 잘하셨으면 Close하시면 됩니다.
