### ISSUE TITLE
Q7) Intent가 뭘까요?

### ISSUE THREAD

**Issue by ows3090** [KamaTAEWOO/FastCampusStudy-1#7]

**Comment by KamaTAEWOO** [comment]
1, 안드로이드 컴포넌트 간에 통신을 하는 데 사용
2, 명시적 인텐트와 암시적 인텐트가 있음
3. 명시적 인텐트는 특정한 컴포넌트를 대상으로 하는 Intent, 암시적 인텐트는 명시적으로 대상을 지정하지 않음

**Comment by ows3090** [comment]
@KamaTAEWOO 태우님
Intent의 정확한 정의는 안드로이드 컴포넌트 간 통신을 위해 사용하는 메세지 객체 입니다.
이해하셨으면 Close 처리하셔도 됩니다.

**Comment by KamaTAEWOO** [comment]
@ows3090 안드로이드 컴포넌트(Activity, Broadcast, Service, Content Provider) 간의 통신을 위해 사용하는 메세지 객체라고 이해하면 괜찮을까요??

**Comment by ows3090** [comment]
@KamaTAEWOO 태우님
그 중에서 하나는 안되는데 한번 알아보세용~!

**Comment by KamaTAEWOO** [comment]
@ows3090 정답은 Content Provider군요! Content Provider은 앱과 앱간의 데이터를 연동하는 목적으로 사용하는 컴포넌트라서 그렇군요!

**Comment by ows3090** [comment]
@KamaTAEWOO 네 맞아요~!
아래 Close issue 누르시면 이슈 닫을 수 있습니다!
