### ISSUE TITLE
Q8) Manifest 파일은 어떤 역할을 할까요?

### ISSUE THREAD

**Issue by ows3090** [KamaTAEWOO/FastCampusStudy-1#8]

**Comment by KamaTAEWOO** [comment]
1. 안드로이드 시스템에서 애플리케이션 정보를 제공하기 위해 사용
2. 권한설정
3. 4대 컴포넌트 선언
4. 생명 주기 관리를 위한 정보를 제공

**Comment by ows3090** [comment]
@KamaTAEWOO 태우님
이해하셨으면 Close하셔도 됩니다.
