### ISSUE TITLE
Q9) Android 4대 컴포넌트를 간략히 설명해주세요

### ISSUE THREAD

**Issue by ows3090** [KamaTAEWOO/FastCampusStudy-1#9]

**Comment by KamaTAEWOO** [comment]
1. 액티비티(Activity): 사용자 인터페이스를 구성하는 컴포넌트로, 애플리케이션 화면을 담당
2. 서비스(Service): 백그라운드에서 실행되는 컴포넌트로, UI가 없이 애플리케이션에서 백그라운드 작업을 처리
3. 브로드캐스트 수신자(Broadcast Receiver): 시스템 또는 애플리케이션이 발생시키는 브로드캐스트 메시지를 수신하여 특정 작업을 수행하는 컴포넌트
4. 콘텐트 제공자(Content Provider): 데이터베이스와 같은 애플리케이션 데이터를 다른 애플리케이션에서 공유하거나 관리하는 컴포넌트

**Comment by ows3090** [comment]
@KamaTAEWOO 태우님
이해하셨으면 Close 하셔도 됩니다.
